application:
  data-source: user # Options: user, Training-Plan

---
# User DataSource Configuration
spring:
  config:
    activate:
      on-profile: user-datasource
  datasource:
    user:
      jdbc-url: jdbc:postgresql://localhost:5432/user_db
      username: user_db_user
      password: user_db_password
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 2
        connection-timeout: 30000
  flyway:
    user:
      enabled: true
      locations: classpath:db/migration/user
      baseline-on-migrate: true
      baseline-version: 0
      schemas: public

---
# Training-Plan DataSource Configuration
spring:
  config:
    activate:
      on-profile: training-plan-datasource
  datasource:
    training-plan:
      jdbc-url: jdbc:postgresql://localhost:5432/training_pan_db
      username: training_pan_user
      password: training_pan_password
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 2
        connection-timeout: 30000
  flyway:
    training-pan:
      enabled: true
      locations: classpath:db/migration/training-pan
      baseline-on-migrate: true
      baseline-version: 0
      schemas: public
